# Generated by Django 2.0.7 on 2019-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
